project:
  type: website

website:
  title: "Posit Test Drive"
  navbar:
    left:
      - href: index.qmd
        text: Content
      - href: help.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left

editor: source