project:
  type: website

website:
  title: "Reproduceable Reporting With Quarto"
  navbar:
      left:
      - href: landing.qmd
        text: Slides
      - href: index.qmd
        text: Examples
      - href: help.qmd
        text: About Posit Team
      right:
      - href: https://github.com/leesahanders/
        text: Lisa Anders
      - icon: github
        href: https://github.com/leesahanders/quarto-for-reproducible-reporting-demo

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left

editor: source