name: connect-publish
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  connect-publish-report-mermaid-diagrams:
    name: connect-publish-report-mermaid-diagrams
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          show-logs: TRUE
          force: TRUE
          dir: ./content-examples/report-mermaid-diagrams/:report-mermaid-diagrams 
  connect-publish-website:
    name: connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          show-logs: TRUE
          force: TRUE
          dir: ./content-examples/website/:website 
  connect-publish-report-lightbox:
    name: connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          show-logs: TRUE
          force: TRUE
          dir: ./content-examples/report-lightbox/:report-lightbox 
  connect-publish-report-hybrid-knitr:
    name: connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          show-logs: TRUE
          force: TRUE
          dir: ./content-examples/report-hybrid-knitr/:report-hybrid-knitr
  connect-publish-report-hybrid-jupyter:
    name: connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          dir: ./content-examples/report-hybrid-jupyter/:report-hybrid-jupyter
  connect-publish-report-commentable:
    name: connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          show-logs: TRUE
          force: TRUE
          dir: ./content-examples/report-commentable/:report-commentable
  connect-publish-report-branded:
    name: connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          show-logs: TRUE
          force: TRUE
          dir: ./content-examples/report-branded/:report-branded
  connect-publish-presentation:
    name: connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          show-logs: TRUE
          force: TRUE
          dir: ./content-examples/presentation/:presentation
  connect-publish-email-programmatic:
    name: connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          show-logs: TRUE
          force: TRUE
          dir: ./content-examples/email-programmatic/:email-programmatic
  connect-publish-email-plots:
    name: connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          show-logs: TRUE
          force: TRUE
          dir: ./content-examples/email-plots/:email-plots
  connect-publish-email-conditional:
    name: connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          show-logs: TRUE
          force: TRUE
          dir: ./content-examples/email-conditional/:email-conditional
  connect-publish-dashboard:
    name: connect-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          show-logs: TRUE
          force: TRUE
          dir: ./content-examples/dashboard/:dashboard
  notify:
    needs: connect-publish
    runs-on: ubuntu-latest
    name: connect-publish-landing-page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0
          use-public-rspm: true
      - name: Publish the app to Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_URL }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          show-logs: TRUE
          force: TRUE
          dir: ./content-examples/landing-page/:landing-page